version: '3.8'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongouser:mongopassword@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongo-data:
se